#!/bin/bash

if [[ ! $# -eq 1 ]]; then
	echo Make sure the tag was created and coincides wit build.zig.zon
	echo
	echo Release notes are ready
	exit 1
fi

TAG=$1

echo "$TAG"

echo gh release upload "$TAG" zig-out/aarch64-linux/tldrtranslate-aarch64-linux \
	zig-out/aarch64-macos/tldrtranslate-aarch64-macos \
	zig-out/x86_64-linux-musl/tldrtranslate-x86_64-linux zig-out/x86_64-macos/tldrtranslate-x86_64-macos zig-out/x86_64-windows/tldrtranslate-x86_64-windows.exe
