name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build and Test
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: @{{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: Run tests
        run: zig build test
